import React, { useEffect, useState } from 'react';
import {
    Box,
    Flex,
    FormControl,
    FormLabel,
    Text,
    Input,
    Image,
    Switch,
    Divider,
    Button,
    Select,
    IconButton,
    Tooltip,
    Skeleton,
} from '@chakra-ui/react';
import { FaUpload } from 'react-icons/fa';

function AddProduct(props) {
    const [isLoaded, setIsLoaded] = useState(false);

    useEffect(() => {
        const delay = setTimeout(() => {
            setIsLoaded(true)
        }, 2000)

        return () => {
            clearTimeout(delay);
        }
    }, []);

    return ( 
        <Box
            h={'86vh'}
            px={'1.5'}
            py={'1.5'}
            w={'100%'}
            rounded={'xl'}
        >
            <Flex
                flexDir={'column'}
                justifyContent={'space-between'}
                h={'100%'}
            >
                <Flex
                    flexDir={'column'}
                    justifyContent={'center'}
                    alignItems={'center'}
                >
                    <Box
                        border={'1px'}
                        borderColor={'white'}
                        position={'relative'}
                        mt={'0.5'}
                    >
                        <Skeleton
                            isLoaded={isLoaded}
                        >
                            <Image
                                objectFit={'cover'}
                                w={'250px'}
                                h={'150px'}
                                src='https://images.unsplash.com/photo-1582252852999-5ca546037481?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'
                                alt='Product Image'
                                color={'white'}
                            />
                        </Skeleton>
                        <Skeleton
                            isLoaded={isLoaded}
                        >
                            <Tooltip
                                label={'Upoad Image'}
                                hasArrow
                                bg={'black'}
                                color={'white'}
                                placement={'left'}
                                closeOnClick={false}
                                fontSize={'xs'}
                            >
                                <IconButton 
                                    icon={<FaUpload/>}
                                    position={'absolute'}
                                    top={'1'}
                                    right={'1'}
                                    size={'xs'}
                                    color={'white'}
                                    bg={'gray.700'}
                                >
                                    <input
                                        type={'file'}
                                    />
                                </IconButton>
                            </Tooltip>
                        </Skeleton>
                    </Box>
                    <Box
                        w={'90%'}
                        py={'1'}
                    >
                        <FormControl>
                            <Skeleton
                                isLoaded={isLoaded}
                                w={'max-content'}
                            >
                                <FormLabel
                                    fontSize={'sm'}
                                    color={'white'}
                                >
                                    Product name
                                </FormLabel>
                            </Skeleton>
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Input
                                    size={'xs'}
                                    color={'black'}
                                    bg={'white'}
                                    variant={'outline'}
                                    type='text'
                                />
                            </Skeleton>
                        </FormControl>
                        <FormControl>
                            <Skeleton
                                isLoaded={isLoaded}
                                w={'max-content'}
                            >
                                <FormLabel
                                    fontSize={'sm'}
                                    color={'white'}
                                    mt={'0.5'}
                                >
                                    Category
                                </FormLabel>
                            </Skeleton>
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Select
                                    placeholder='Select Category'
                                    size={'xs'}
                                    variant={'outline'}
                                    color={'black'}
                                    bg={'white'}
                                >
                                    <option>
                                        category 1
                                    </option>
                                </Select>
                            </Skeleton>
                        </FormControl>
                        <FormControl>
                            <Skeleton
                                isLoaded={isLoaded}
                                w={'max-content'}
                            >
                                <FormLabel
                                    fontSize={'sm'}
                                    color={'white'}
                                    mt={'0.5'}
                                >
                                    Stock
                                </FormLabel>
                            </Skeleton>
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Input
                                    size={'xs'}
                                    color={'black'}
                                    bg={'white'}
                                    variant={'outline'}
                                    type='number'
                                />
                            </Skeleton>
                        </FormControl>
                        <FormControl>
                            <Skeleton
                                isLoaded={isLoaded}
                                w={'max-content'}
                            >
                                <FormLabel
                                    fontSize={'sm'}
                                    color={'white'}
                                    mt={'0.5'}
                                >
                                    Price
                                </FormLabel>
                            </Skeleton>
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Input
                                    size={'xs'}
                                    color={'black'}
                                    bg={'white'}
                                    variant={'outline'}
                                    type='number'
                                />
                            </Skeleton>
                        </FormControl>
                    </Box>
                    <Box
                        w={'90%'}
                    >
                        <Flex
                            justifyContent={'start'}
                            alignItems={'start'}
                            flexDir={'column'}
                            gap={'0.5'}
                        >
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Text
                                    color={'white'}
                                    fontSize={'sm'}
                                >
                                    Status
                                </Text>
                            </Skeleton>
                            <Flex
                                alignItems={'center'}
                                gap={'4'}
                            >
                                <Skeleton
                                    isLoaded={isLoaded}
                                >
                                    <Switch
                                        colorScheme={'green'}
                                    />
                                </Skeleton>
                                <Skeleton
                                    isLoaded={isLoaded}
                                >
                                    <Text
                                        color={'green.500'}
                                    >
                                        Active
                                    </Text>
                                </Skeleton>
                            </Flex>
                        </Flex>
                    </Box>
                </Flex>
                <Flex
                    justifyContent={'center'}
                    alignItems={'center'}
                    flexDir={'column'}
                    gap={'3'}
                    mb={'2'}
                >
                    <Box
                        w={'90%'}
                    >
                        <Divider/>
                    </Box>
                    <Flex
                        w={'90%'}
                        justifyContent={'space-evenly'}
                        pt={'0.5'}
                    >
                        <Box>
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Button
                                    size={'sm'}
                                    colorScheme={'red'}
                                    color={'white'}
                                    onClick={() => props.handleCloseComponent()}
                                >
                                    Close
                                </Button>
                            </Skeleton>
                        </Box>
                        <Flex
                            justifyContent={'center'}
                            w={'30%'}
                        >
                            <Skeleton
                                isLoaded={isLoaded}
                            >
                                <Button
                                    size={'sm'}
                                    colorScheme={'green'}
                                    color={'white'}
                                >
                                    Create
                                </Button>
                            </Skeleton>
                        </Flex>
                    </Flex>
                </Flex>
            </Flex>
        </Box>
     );
}

export default AddProduct;